server:
  port: 8099
 

#server.servlet.context-path=/memberModule
Authorization.URL: ${AUTH_URL:http://localhost}:8008/authorization
Claims.URL:  ${CLAIMS_URL:http://localhost}:8010/claimModule
Policy.URL: ${POLICY_URL:http://localhost}:8081
APIGATEWAY.URL: ${API_URL:http://localhost}:8881/claimModule
 
 
 
spring:
  datasource:
    url: jdbc:h2:mem:local
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console.enabled: true
    console:
      settings:
        web-allow-others: true
  cloud:
    compatibility-verifier:
      enabled: false  
    config:
      enabled: false


